### ISSUE TITLE
What does ... do?

### ISSUE THREAD

**Issue by iamnewton** [davidkpiano/sass-specificity#1]
What does the [`...`](https://github.com/davidkpiano/sass-specificity/blob/master/specificity/_specificity.scss#L122) do?  I been trying to add this to my debug library and it fails on this line as invalid.

**Comment by davidkpiano** [comment]
It's supposed to be a spread operator but I don't remember 100% - I wrote this 3 years ago 😅

**Comment by iamnewton** [comment]
Understandable.  Does this come as part of `scss`? Or `compass`?

**Comment by davidkpiano** [comment]
It's part of Sass itself. See here: http://sass-lang.com/documentation/file.SASS_REFERENCE.html#Variable_Arguments

**Comment by iamnewton** [comment]
Is this not available in lib-sass or node-sass?

**Comment by iamnewton** [comment]
Thanks so much for all the help.
